version: '3.4'

services:
  app:
    container_name: directory-lister-app
    build: .
    image: directory-lister-dev:local
    depends_on:
      - memcached
      - redis
    environment:
      MEMCACHED_HOST: memcached
      REDIS_HOST: redis
      VIRTUAL_HOST: directory-lister.local
    ports:
      - ${APP_PORT:-80}:80
    extra_hosts:
      - host.docker.internal:${DOCKER_HOST_IP:-172.17.0.1}
    user: ${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}
    volumes:
      - ./:/var/www/html

  memcached:
    container_name: directory-lister-memcached
    ports:
      - ${MEMCACHED_PORT:-11211}:11211
    image: memcached:1.6

  redis:
    container_name: directory-lister-redis
    ports:
      - ${REDIS_PORT:-6379}:6379
    image: redis:6.0

  npm:
    container_name: directory-lister-npm
    image: directory-lister-dev:local
    volumes:
      - ./:/var/www/html
    user: ${HOST_USER_ID:-0}:${HOST_GROUP_ID:-0}
    command: npm run watch
